export { default as Heading } from "./heading/Heading";
// export { default as Text } from "./text/Text";
export { default as Container } from "./container/Container";
export { default as Button } from "./button/Button";
export { default as FormInput } from "./FormInput/FormInput";
export { default as FormText } from "./FormInput/FormText";
// export { default as Card } from "./card/Card";
export { default as Grid } from "./grid/Grid";
// export { default as Divider } from "./divider/Divider";
// export { default as InfoItem } from "./infoItem/InfoItem";
// export { default as ProductSlider } from "./productSlider/ProductSlider";
// export { default as CategoryCard } from "./categoryCard/CategoryCard";

// export { default as Review } from "./reviews/Reviews";
export { default as LinkBtn } from "./linkBtn/LinkBtn";
// export { default as ImageSlider } from "./imageSlider/ImageSlider";
export { default as Messages } from "./messages/Messages";
// export { default as Selector } from "./selector/Selector";
export { default as Modal } from "./modal/Modal";
// export { default as UserCard } from "./userCard/UserCard";
// export { default as GoBackBtn } from "./goBackBtn/GoBackBtn";
